// TEMPORARY DATA

export let role = "admin";

export const teachersData = [
  {
    id: 1,
    maestroId: "1234567890",
    nombre: "John Doe",
    email: "john@doe.com",
    foto:
      "https://images.pexels.com/photos/2888150/pexels-photo-2888150.jpeg?auto=compress&cs=tinysrgb&w=1200",
    telefono: "1234567890",
    materias: ["Math", "Geometry"],
    clases: ["1B", "2A", "3C"],
    direccion: "123 Main St, Anytown, USA",
  },
  {
    id: 2,
    maestroId: "1234567890",
    nombre: "Jane Doe",
    email: "jane@doe.com",
    foto:
      "https://images.pexels.com/photos/936126/pexels-photo-936126.jpeg?auto=compress&cs=tinysrgb&w=1200",
    telefono: "1234567890",
    materias: ["Physics", "Chemistry"],
    clases: ["5A", "4B", "3C"],
    direccion: "123 Main St, Anytown, USA",
  },
  {
    id: 3,
    maestroId: "1234567890",
    nombre: "Mike Geller",
    email: "mike@geller.com",
    foto:
      "https://images.pexels.com/photos/428328/pexels-photo-428328.jpeg?auto=compress&cs=tinysrgb&w=1200",
    telefono: "1234567890",
    materias: ["Biology"],
    clases: ["5A", "4B", "3C"],
    direccion: "123 Main St, Anytown, USA",
  },
  {
    id: 4,
    maestroId: "1234567890",
    nombre: "Jay French",
    email: "jay@gmail.com",
    foto:
      "https://images.pexels.com/photos/1187765/pexels-photo-1187765.jpeg?auto=compress&cs=tinysrgb&w=1200",
    telefono: "1234567890",
    materias: ["History"],
    clases: ["5A", "4B", "3C"],
    direccion: "123 Main St, Anytown, USA",
  },
  {
    id: 5,
    maestroId: "1234567890",
    nombre: "Jane Smith",
    email: "jane@gmail.com",
    foto:
      "https://images.pexels.com/photos/1102341/pexels-photo-1102341.jpeg?auto=compress&cs=tinysrgb&w=1200",
    telefono: "1234567890",
    materias: ["Music", "History"],
    clases: ["5A", "4B", "3C"],
    direccion: "123 Main St, Anytown, USA",
  },
  {
    id: 6,
    maestroId: "1234567890",
    nombre: "Anna Santiago",
    email: "anna@gmail.com",
    foto:
      "https://images.pexels.com/photos/712513/pexels-photo-712513.jpeg?auto=compress&cs=tinysrgb&w=1200",
    telefono: "1234567890",
    materias: ["Physics"],
    clases: ["5A", "4B", "3C"],
    direccion: "123 Main St, Anytown, USA",
  },
  {
    id: 7,
    maestroId: "1234567890",
    nombre: "Allen Black",
    email: "allen@black.com",
    foto:
      "https://images.pexels.com/photos/1438081/pexels-photo-1438081.jpeg?auto=compress&cs=tinysrgb&w=1200",
    telefono: "1234567890",
    materias: ["English", "Spanish"],
    clases: ["5A", "4B", "3C"],
    direccion: "123 Main St, Anytown, USA",
  },
  {
    id: 8,
    maestroId: "1234567890",
    nombre: "Ophelia Castro",
    email: "ophelia@castro.com",
    foto:
      "https://images.pexels.com/photos/1036623/pexels-photo-1036623.jpeg?auto=compress&cs=tinysrgb&w=1200",
    telefono: "1234567890",
    materias: ["Math", "Geometry"],
    clases: ["5A", "4B", "3C"],
    direccion: "123 Main St, Anytown, USA",
  },
  {
    id: 9,
    maestroId: "1234567890",
    nombre: "Derek Briggs",
    email: "derek@briggs.com",
    foto:
      "https://images.pexels.com/photos/842980/pexels-photo-842980.jpeg?auto=compress&cs=tinysrgb&w=1200",
    telefono: "1234567890",
    materias: ["Literature", "English"],
    clases: ["5A", "4B", "3C"],
    direccion: "123 Main St, Anytown, USA",
  },
  {
    id: 10,
    maestroId: "1234567890",
    nombre: "John Glover",
    email: "john@glover.com",
    foto:
      "https://images.pexels.com/photos/1043474/pexels-photo-1043474.jpeg?auto=compress&cs=tinysrgb&w=1200",
    telefono: "1234567890",
    materias: ["Biology"],
    clases: ["5A", "4B", "3C"],
    direccion: "123 Main St, Anytown, USA",
  },
];

export const studentsData = [
  {
    id: 1,
    alumnoId: "1234567890",
    nombre: "Nahwel Carreras",
    email: "nahwel@gmail.com",
    foto:
      "https://images.pexels.com/photos/2888150/pexels-photo-2888150.jpeg?auto=compress&cs=tinysrgb&w=1200",
    telefono: "1234567890",
    grado: 5,
    clase: "1B",
    direccion: "1012 Treinta y tres, Sarandi Grande, Florida, Uruguay",
  },
  {
    id: 2,
    alumnoId: "1234567890",
    nombre: "Jane Doe",
    email: "jane@doe.com",
    foto:
      "https://images.pexels.com/photos/936126/pexels-photo-936126.jpeg?auto=compress&cs=tinysrgb&w=1200",
    telefono: "1234567890",
    grado: 5,
    clase: "5A",
    direccion: "123 Main St, Anytown, USA",
  },
  {
    id: 3,
    alumnoId: "1234567890",
    nombre: "Mike Geller",
    email: "mike@geller.com",
    foto:
      "https://images.pexels.com/photos/428328/pexels-photo-428328.jpeg?auto=compress&cs=tinysrgb&w=1200",
    telefono: "1234567890",
    grado: 5,
    clase: "5A",
    direccion: "123 Main St, Anytown, USA",
  },
  {
    id: 4,
    alumnoId: "1234567890",
    nombre: "Jay French",
    email: "jay@gmail.com",
    foto:
      "https://images.pexels.com/photos/1187765/pexels-photo-1187765.jpeg?auto=compress&cs=tinysrgb&w=1200",
    telefono: "1234567890",
    grado: 5,
    clase: "5A",
    direccion: "123 Main St, Anytown, USA",
  },
  {
    id: 5,
    alumnoId: "1234567890",
    nombre: "Jane Smith",
    email: "jane@gmail.com",
    foto:
      "https://images.pexels.com/photos/1102341/pexels-photo-1102341.jpeg?auto=compress&cs=tinysrgb&w=1200",
    telefono: "1234567890",
    grado: 5,
    clase: "5A",
    direccion: "123 Main St, Anytown, USA",
  },
  {
    id: 6,
    alumnoId: "1234567890",
    nombre: "Anna Santiago",
    email: "anna@gmail.com",
    foto:
      "https://images.pexels.com/photos/712513/pexels-photo-712513.jpeg?auto=compress&cs=tinysrgb&w=1200",
    telefono: "1234567890",
    grado: 5,
    clase: "5A",
    direccion: "123 Main St, Anytown, USA",
  },
  {
    id: 7,
    alumnoId: "1234567890",
    nombre: "Allen Black",
    email: "allen@black.com",
    foto:
      "https://images.pexels.com/photos/1438081/pexels-photo-1438081.jpeg?auto=compress&cs=tinysrgb&w=1200",
    telefono: "1234567890",
    grado: 5,
    clase: "5A",
    direccion: "123 Main St, Anytown, USA",
  },
  {
    id: 8,
    alumnoId: "1234567890",
    nombre: "Ophelia Castro",
    email: "ophelia@castro.com",
    foto:
      "https://images.pexels.com/photos/1036623/pexels-photo-1036623.jpeg?auto=compress&cs=tinysrgb&w=1200",
    telefono: "1234567890",
    grado: 5,
    clase: "5A",
    direccion: "123 Main St, Anytown, USA",
  },
  {
    id: 9,
    alumnoId: "1234567890",
    nombre: "Derek Briggs",
    email: "derek@briggs.com",
    foto:
      "https://images.pexels.com/photos/842980/pexels-photo-842980.jpeg?auto=compress&cs=tinysrgb&w=1200",
    telefono: "1234567890",
    grado: 5,
    clase: "5A",
    direccion: "123 Main St, Anytown, USA",
  },
  {
    id: 10,
    alumnoId: "1234567890",
    nombre: "John Glover",
    email: "john@glover.com",
    foto:
      "https://images.pexels.com/photos/1043474/pexels-photo-1043474.jpeg?auto=compress&cs=tinysrgb&w=1200",
    telefono: "1234567890",
    grado: 5,
    clase: "5A",
    direccion: "123 Main St, Anytown, USA",
  },
];

export const parentsData = [
  {
    id: 1,
    name: "John Doe",
    students: ["Sarah Brewer"],
    email: "john@doe.com",
    phone: "1234567890",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 2,
    name: "Jane Doe",
    students: ["Cecilia Bradley"],
    email: "jane@doe.com",
    phone: "1234567890",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 3,
    name: "Mike Geller",
    students: ["Fanny Caldwell"],
    email: "mike@geller.com",
    phone: "1234567890",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 4,
    name: "Jay French",
    students: ["Mollie Fitzgerald", "Ian Bryant"],
    email: "mike@geller.com",
    phone: "1234567890",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 5,
    name: "Jane Smith",
    students: ["Mable Harvey"],
    email: "mike@geller.com",
    phone: "1234567890",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 6,
    name: "Anna Santiago",
    students: ["Joel Lambert"],
    email: "mike@geller.com",
    phone: "1234567890",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 7,
    name: "Allen Black",
    students: ["Carrie Tucker", "Lilly Underwood"],
    email: "mike@geller.com",
    phone: "1234567890",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 8,
    name: "Ophelia Castro",
    students: ["Alexander Blair"],
    email: "mike@geller.com",
    phone: "1234567890",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 9,
    name: "Derek Briggs",
    students: ["Susan Webster", "Maude Stone"],
    email: "mike@geller.com",
    phone: "1234567890",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 10,
    name: "John Glover",
    students: ["Stella Scott"],
    email: "mike@geller.com",
    phone: "1234567890",
    address: "123 Main St, Anytown, USA",
  },
];

export const subjectsData = [
  {
    id: 1,
    nombre: "Bateria",
    maestros: ["Marcelo Alejandro Amaro"],
  },
  {
    id: 2,
    nombre: "English",
    maestros: ["Manuel Becker", "Eddie Chavez"],
  },
  {
    id: 3,
    nombre: "Physics",
    maestros: ["Lola Newman", "Darrell Delgado"],
  },
  {
    id: 4,
    nombre: "Chemistry",
    maestros: ["Nathan Kelly", "Benjamin Snyder"],
  },
  {
    id: 5,
    nombre: "Biology",
    maestros: ["Alma Benson", "Lina Collier"],
  },
  {
    id: 6,
    nombre: "History",
    maestros: ["Hannah Bowman", "Betty Obrien"],
  },
  {
    id: 7,
    nombre: "Geography",
    maestros: ["Lora French", "Sue Brady"],
  },
  {
    id: 8,
    nombre: "Art",
    maestros: ["Harriet Alvarado", "Mayme Keller"],
  },
  {
    id: 9,
    nombre: "Music",
    maestros: ["Gertrude Roy", "Rosa Singleton"],
  },
  {
    id: 10,
    nombre: "Literature",
    maestros: ["Effie Lynch", "Brett Flowers"],
  },
];

export const classesData = [
  {
    id: 1,
    nombre: "1A",
    capacidad: 20,
    grado: 1,
    supervisor: "Joseph Padilla",
  },
  {
    id: 2,
    nombre: "2B",
    capacidad: 22,
    grado: 2,
    supervisor: "Blake Joseph",
  },
  {
    id: 3,
    nombre: "3C",
    capacidad: 20,
    grado: 3,
    supervisor: "Tom Bennett",
  },
  {
    id: 4,
    nombre: "4B",
    capacidad: 18,
    grado: 4,
    supervisor: "Aaron Collins",
  },
  {
    id: 5,
    nombre: "5A",
    capacidad: 16,
    grado: 5,
    supervisor: "Iva Frank",
  },
  {
    id: 5,
    nombre: "5B",
    capacidad: 20,
    grado: 5,
    supervisor: "Leila Santos",
  },
  {
    id: 7,
    nombre: "7A",
    capacidad: 18,
    grado: 7,
    supervisor: "Carrie Walton",
  },
  {
    id: 8,
    nombre: "6B",
    capacidad: 22,
    grado: 6,
    supervisor: "Christopher Butler",
  },
  {
    id: 9,
    nombre: "6C",
    capacidad: 18,
    grado: 6,
    supervisor: "Marc Miller",
  },
  {
    id: 10,
    nombre: "6D",
    capacidad: 20,
    grado: 6,
    supervisor: "Ophelia Marsh",
  },
];

export const lessonsData = [
  {
    id: 1,
    materia: "Math",
    clase: "1A",
    maestro: "Tommy Wise",
  },
  {
    id: 2,
    materia: "English",
    clase: "2A",
    maestro: "Rhoda Frank",
  },
  {
    id: 3,
    materia: "Science",
    clase: "3A",
    maestro: "Della Dunn",
  },
  {
    id: 4,
    materia: "Social Studies",
    clase: "1B",
    maestro: "Bruce Rodriguez",
  },
  {
    id: 5,
    materia: "Art",
    clase: "4A",
    maestro: "Birdie Butler",
  },
  {
    id: 6,
    materia: "Music",
    clase: "5A",
    maestro: "Bettie Oliver",
  },
  {
    id: 7,
    materia: "History",
    clase: "6A",
    maestro: "Herman Howard",
  },
  {
    id: 8,
    materia: "Geography",
    clase: "6B",
    maestro: "Lucinda Thomas",
  },
  {
    id: 9,
    materia: "Physics",
    clase: "6C",
    maestro: "Ronald Roberts",
  },
  {
    id: 10,
    materia: "Chemistry",
    clase: "4B",
    maestro: "Julia Pittman",
  },
];

export const examsData = [
  {
    id: 1,
    materia: "Math",
    clase: "1A",
    maestro: "Martha Morris",
    fecha: "2025-01-01",
  },
  {
    id: 2,
    materia: "English",
    clase: "2A",
    maestro: "Randall Garcia",
    fecha: "2025-01-01",
  },
  {
    id: 3,
    materia: "Science",
    clase: "3A",
    maestro: "Myrtie Scott",
    fecha: "2025-01-01",
  },
  {
    id: 4,
    materia: "Social Studies",
    clase: "1B",
    maestro: "Alvin Swanson",
    fecha: "2025-01-01",
  },
  {
    id: 5,
    materia: "Art",
    clase: "4A",
    maestro: "Mabelle Wallace",
    fecha: "2025-01-01",
  },
  {
    id: 6,
    materia: "Music",
    clase: "5A",
    maestro: "Dale Thompson",
    fecha: "2025-01-01",
  },
  {
    id: 7,
    materia: "History",
    clase: "6A",
    maestro: "Allie Conner",
    fecha: "2025-01-01",
  },
  {
    id: 8,
    materia: "Geography",
    clase: "6B",
    maestro: "Hunter Fuller",
    fecha: "2025-01-01",
  },
  {
    id: 9,
    materia: "Physics",
    clase: "7A",
    maestro: "Lois Lindsey",
    fecha: "2025-01-01",
  },
  {
    id: 10,
    materia: "Chemistry",
    clase: "8A",
    maestro: "Vera Soto",
    fecha: "2025-01-01",
  },
];

export const assignmentsData = [
  {
    id: 1,
    materia: "Math",
    clase: "1A",
    maestro: "Anthony Boone",
    dueFecha: "2025-01-01",
  },
  {
    id: 2,
    materia: "English",
    clase: "2A",
    maestro: "Clifford Bowen",
    dueFecha: "2025-01-01",
  },
  {
    id: 3,
    materia: "Science",
    clase: "3A",
    maestro: "Catherine Malone",
    dueFecha: "2025-01-01",
  },
  {
    id: 4,
    materia: "Social Studies",
    clase: "1B",
    maestro: "Willie Medina",
    dueFecha: "2025-01-01",
  },
  {
    id: 5,
    materia: "Art",
    clase: "4A",
    maestro: "Jose Ruiz",
    dueFecha: "2025-01-01",
  },
  {
    id: 6,
    materia: "Music",
    clase: "5A",
    maestro: "Katharine Owens",
    dueFecha: "2025-01-01",
  },
  {
    id: 7,
    materia: "History",
    clase: "6A",
    maestro: "Shawn Norman",
    dueFecha: "2025-01-01",
  },
  {
    id: 8,
    materia: "Geography",
    clase: "6B",
    maestro: "Don Holloway",
    dueFecha: "2025-01-01",
  },
  {
    id: 9,
    materia: "Physics",
    clase: "7A",
    maestro: "Franklin Gregory",
    dueFecha: "2025-01-01",
  },
  {
    id: 10,
    materia: "Chemistry",
    clase: "8A",
    maestro: "Danny Nguyen",
    dueFecha: "2025-01-01",
  },
];

export const resultsData = [
  {
    id: 1,
    materia: "Math",
    clase: "1A",
    maestro: "John Doe",
    estudiante: "John Doe",
    fecha: "2025-01-01",
    tipo: "exam",
    puntaje: 90,
  },
  {
    id: 2,
    materia: "English",
    clase: "2A",
    maestro: "John Doe",
    estudiante: "John Doe",
    fecha: "2025-01-01",
    tipo: "exam",
    puntaje: 90,
  },
  {
    id: 3,
    materia: "Science",
    clase: "3A",
    maestro: "John Doe",
    estudiante: "John Doe",
    fecha: "2025-01-01",
    tipo: "exam",
    puntaje: 90,
  },
  {
    id: 4,
    materia: "Social Studies",
    clase: "1B",
    maestro: "John Doe",
    estudiante: "John Doe",
    fecha: "2025-01-01",
    tipo: "exam",
    puntaje: 90,
  },
  {
    id: 5,
    materia: "Art",
    clase: "4A",
    maestro: "John Doe",
    estudiante: "John Doe",
    fecha: "2025-01-01",
    tipo: "exam",
    puntaje: 90,
  },
  {
    id: 6,
    materia: "Music",
    clase: "5A",
    maestro: "John Doe",
    estudiante: "John Doe",
    fecha: "2025-01-01",
    tipo: "exam",
    puntaje: 90,
  },
  {
    id: 7,
    materia: "History",
    clase: "6A",
    maestro: "John Doe",
    estudiante: "John Doe",
    fecha: "2025-01-01",
    tipo: "exam",
    puntaje: 90,
  },
  {
    id: 8,
    materia: "Geography",
    clase: "6B",
    maestro: "John Doe",
    estudiante: "John Doe",
    fecha: "2025-01-01",
    tipo: "exam",
    puntaje: 90,
  },
  {
    id: 9,
    materia: "Physics",
    clase: "7A",
    maestro: "John Doe",
    estudiante: "John Doe",
    fecha: "2025-01-01",
    tipo: "exam",
    puntaje: 90,
  },
  {
    id: 10,
    materia: "Chemistry",
    clase: "8A",
    maestro: "John Doe",
    estudiante: "John Doe",
    fecha: "2025-01-01",
    tipo: "exam",
    puntaje: 90,
  },
];

export const eventsData = [
  {
    id: 1,
    titulo: "Lake Trip",
    clases: "1A",
    fecha: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 2,
    titulo: "Picnic",
    clases: "2A",
    fecha: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 3,
    titulo: "Beach Trip",
    clases: "3A",
    fecha: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 4,
    titulo: "Museum Trip",
    clases: "4A",
    fecha: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 5,
    titulo: "Music Concert",
    clases: "5A",
    fecha: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 6,
    titulo: "Magician Show",
    clases: "1B",
    fecha: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 7,
    titulo: "Lake Trip",
    clases: "2B",
    fecha: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 8,
    titulo: "Cycling Race",
    clases: "3B",
    fecha: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 9,
    titulo: "Art Exhibition",
    clases: "4B",
    fecha: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 10,
    titulo: "Sports Tournament",
    clases: "5B",
    fecha: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
];

export const announcementsData = [
  {
    id: 1,
    titulo: "About 4A Math Test",
    clase: "4A",
    fecha: "2025-01-01",
  },
  {
    id: 2,
    titulo: "About 3A Math Test",
    clase: "3A",
    fecha: "2025-01-01",
  },
  {
    id: 3,
    titulo: "About 3B Math Test",
    clase: "3B",
    fecha: "2025-01-01",
  },
  {
    id: 4,
    titulo: "About 6A Math Test",
    clase: "6A",
    fecha: "2025-01-01",
  },
  {
    id: 5,
    titulo: "About 8C Math Test",
    clase: "8C",
    fecha: "2025-01-01",
  },
  {
    id: 6,
    titulo: "About 2A Math Test",
    clase: "2A",
    fecha: "2025-01-01",
  },
  {
    id: 7,
    titulo: "About 4C Math Test",
    clase: "4C",
    fecha: "2025-01-01",
  },
  {
    id: 8,
    titulo: "About 4B Math Test",
    clase: "4B",
    fecha: "2025-01-01",
  },
  {
    id: 9,
    titulo: "About 3C Math Test",
    clase: "3C",
    fecha: "2025-01-01",
  },
  {
    id: 10,
    titulo: "About 1C Math Test",
    clase: "1C",
    fecha: "2025-01-01",
  },
];

export const cancionesData = [
  {
    id: 1,
    nombre: "Rock Uruguayo",
    foto: "/uruguay.png",
    
  },
  {
    id: 2,
    nombre: "Rock Argentino",
    foto: "/argentina.png",
    
  },
  {
    id: 3,
    nombre: "Rock en Ingles",
    foto: "/inglaterra.png",
    
  },
  {
    id: 4,
    nombre: "OldHits",
    foto: "/oldhits.png",
    
  },
  {
    id: 5,
    nombre: "Reggae",
    foto: "/reggae.png",
  },
  
];


// YOU SHOULD CHANGE THE DATES OF THE EVENTS TO THE CURRENT DATE TO SEE THE EVENTS ON THE CALENDAR
export const calendarEvents = [
  {
    title: "Correa",
    allDay: false,
    start: new Date(2025, 10, 17, 19, 0),
    end: new Date(2025, 10, 17, 20, 0),
  },
  {
    title: "Nahwel",
    allDay: false,
    start: new Date(2025, 10, 18, 18, 30),
    end: new Date(2025, 10, 18, 19, 30),
  },
  {
    title: "Luciana",
    allDay: false,
    start: new Date(2025, 10, 19, 18, 0),
    end: new Date(2025, 10, 19, 19, 0),
  },
  {
    title: "Lolo",
    allDay: false,
    start: new Date(2025, 10, 19, 19, 0),
    end: new Date(2025, 10, 19, 20, 0),
  },
  {
    title: "Nahwel",
    allDay: false,
    start: new Date(2025, 10, 20, 18, 0),
    end: new Date(2025, 10, 20, 19, 0),
  },
  {
    title: "Edgardo",
    allDay: false,
    start: new Date(2025, 10, 20, 20, 0),
    end: new Date(2025, 10, 20, 21, 0),
  },
  {
    title: "Bauti",
    allDay: false,
    start: new Date(2025, 10, 21, 10, 30),
    end: new Date(2025, 10, 21, 11, 30),
  },
];